fix: handle cleanup operations by signal caught
Instead of putting the onus of handling user-terminated signals (eg:
SIGTERM or SIGINT) in the _operation_title() function, all abnormal
signals are handled via the _cleanup() function.

This keeps signal handling in one location and as a result, the
cleanup() function was refactored to process cleanup of temporary files
on abnormal signals, separating script exit (eg: EXIT) from processing
operations which would handle those temporaray files.

This refactoring came from introduced bugs by converting $operations[@]
from manually setting each operation by index number to generating a new
array of all operations to run and generating the correct order
automatically.

It became apparent after introduction LAC support that all the
operations tied to an array index would have to be re-ordered, which
made the move to automatic assignment preferable.

diff --git a/redoflacs b/redoflacs
--- a/redoflacs
+++ b/redoflacs
@@ -287,7 +287,7 @@ _runtime_banner()
 #
 _operation_title()
 {
-  local fmt match op status_banner issues_banner right_align
+  local fmt status_banner issues_banner right_align
   local -i issues="$(_num_issues)"  # Total number of issues found
 
   # Ensure we do not run if running from a countdown or before an
@@ -343,45 +343,6 @@ _operation_title()
 
   # Display generated operation title message
   printf "$fmt" "${operation_title[$operation]}"
-
-  # If a user sent SIGINT or if an operation completed but had some
-  # issues, then the subsequent operations which would have run are
-  # displayed, if any
-  #
-  # NOTE:
-  #   The parent function will be the signal handler for SIGINT
-  if
-    [[ "${FUNCNAME[1]}" == '_cleanup' ]] \
-    || (( issues > 0 && num == ${#total_items[@]} ))
-  then
-    # Loop through all operations and display only the operations which
-    # have not run
-    for op in "${operations[@]}"; do
-      # Matched operation is either interrupted or completed with issues
-      [[ "$op" == "$operation" ]] && match='true' && continue
-
-      # Skip completed operations (without issues)
-      [[ ! "$match" ]] && continue
-
-      status_banner='DID NOT RUN'
-
-      # Determine where to place cursor in terminal column to right
-      # align the operation status
-      right_align=$(( MAX_LENGTH - ${#status_banner} ))
-
-      fmt=" ${green}*$reset "  # Colored title prefix
-      fmt+='%s'                # Modifier; title of operation
-
-      # Cursor at operation title; right-aligned for issues banner
-      fmt+=$"\033[$(_row);${right_align}H"
-
-      # Operation status banner
-      fmt+="${magenta}${status_banner}$reset\n"
-
-      # Display generated operation title message
-      printf "$fmt" "${operation_title[$op]}"
-    done
-  fi
 }
 
 #
@@ -473,19 +434,27 @@ _print_item_half() { printf "\033[${row}H$yellow 50%%$reset";  }
 _print_item_skip() { printf "\033[${row}H${cyan}skip$reset";   }
 
 #
-# Kill any children process and perform cleanup, checking for the
-# existence of a log file before exiting script
+# Manage termination and cleanup of this script
 #
 # The signal captured by this function is $1, generated by the trap
 #
+# NOTE:
+#   This function may run twice, one for caught signals and one after
+#   script completion/exit
+#
+#   As a result, abnormal signals caught will perform cleanup by
+#   removing files and killing any jobs which may be running
+#
 _cleanup()
 {
-  # The signal received by the trap
-  local signal_received="${1:-EXIT}"
+  local i fmt op match status_banner right_align
 
-  # Kill all children if the user interrupted the script and clean up
-  # the current items processed from the screen
-  if [[ "$signal_received" == 'SIGINT' ]]; then
+  local signal_received="${1:-EXIT}"  # Signal received by trap
+  local -i issues="$(_num_issues)"    # Total number of issues found
+
+  # Abnormal termination will terminate running jobs and remove
+  # temporary files
+  if [[ "$signal_received" != 'EXIT' ]]; then
     _kill_jobs "$(jobs -rp)"
 
     # Clear all the operation lines by moving up each line and clearing
@@ -497,29 +466,67 @@ _cleanup()
     # Display title message of operation
     _operation_title
 
-    exit 130
+    # Loop through all operations and display only the operations which
+    # have not run
+    for op in "${operations[@]}"; do
+      # Matched operation is either interrupted or completed with issues
+      [[ "$op" == "$operation" ]] && match='true' && continue
+
+      # Skip completed operations (without issues)
+      [[ ! "$match" ]] && continue
+
+      status_banner='DID NOT RUN'
+
+      # Determine where to place cursor in terminal column to right
+      # align the operation status
+      right_align=$(( MAX_LENGTH - ${#status_banner} ))
+
+      fmt=" ${green}*$reset "  # Colored title prefix
+      fmt+='%s'                # Modifier; title of operation
+
+      # Cursor at operation title; right-aligned for issues banner
+      fmt+=$"\033[$(_row);${right_align}H"
+
+      # Operation status banner
+      fmt+="${magenta}${status_banner}$reset\n"
+
+      # Display generated operation title message
+      printf "$fmt" "${operation_title[$op]}"
+    done
+
+    # Remove temporary WAV and FLAC files
+    rm -rf "${temporary_wav_location_sub_dir:-/dev/null/foo}"
+    rm -f "${directory:-/dev/null/foo}"/**/*_redoflacs_$$.wav
+    rm -f "${directory:-/dev/null/foo}"/**/*.tmp,fl-ac+en\'c
+
+    # Remove temporary picture blocks (from artwork extraction)
+    rm -f /tmp/redoflacs_picture_blocks.[[:digit:]]*
   fi
 
-  # Display extra newline if interruption during countdown
-  [[ "${FUNCNAME[1]}" == '_countdown_metadata' ]] && printf '\n'
+  # Normal script termination checks for any logs and performs cleanup
+  # of script-created files
+  if [[ "$signal_received" == 'EXIT' ]]; then
+    # Ensure user is notified of a log file on script interruption/exit
+    [[ -f "$log_file" ]] && _display_issues_exist
 
-  # Remove temporary WAV and FLAC files
-  rm -rf "${temporary_wav_location_sub_dir:-/dev/null/foo}"
-  rm -f "${directory:-/dev/null/foo}"/**/*_redoflacs_$$.wav
-  rm -f "${directory:-/dev/null/foo}"/**/*.tmp,fl-ac+en\'c
+    # Display extra newline if interruption during countdown
+    [[ "${FUNCNAME[1]}" == '_countdown_metadata' ]] && printf '\n'
 
-  # Remove temporary picture blocks (from artwork extraction)
-  rm -f /tmp/redoflacs_picture_blocks.[[:digit:]]*
+    # Remove temporary job FIFO and temporary errors/issues file
+    rm -f "${job_fifo:-/dev/null/foo}"
+    rm -f "${issue_ticks:-/dev/null/foo}"
 
-  # Remove temporary job FIFO and temporary errors/issues file
-  rm -f "${job_fifo:-/dev/null/foo}"
-  rm -f "${issue_ticks:-/dev/null/foo}"
+    # Restore terminal cursor
+    printf '\033[?25h'
+  fi
 
-  printf '\033[?25h'           # Restore the cursor
+  # Return standard exit codes based on signal received or issues found
+  [[ "$signal_received" == 'SIGINT' ]] && exit 130
+  [[ "$signal_received" == 'SIGTERM' ]] && exit 143
+  (( issues > 0 )) && exit 1
 
-  # Ensure user is notified of a log file on script interruption/exit
-  [[ -f "$log_file" ]] && _display_issues_exist
-  exit 1
+  # Completed without issue
+  exit 0
 }
 
 #
@@ -1013,7 +1020,7 @@ _process_arguments()
     compress_threads
 
   local arg invalid op
-  local -a conflicting
+  local -a conflicting operations_to_run
 
   # If no arguments are made to the script show usage and help
   if (( $# == 0 )); then
@@ -1055,17 +1062,17 @@ _process_arguments()
       'x') no_extra_tags='true' ;;
 
       # Validate MD5 checksum in FLAC files
-      'm') operations[0]='_md5check' ;;
+      'm') operations_to_run+=( '_md5check' ) ;;
 
       # Test FLAC files
-      't') operations[1]='_test' ;;
+      't') operations_to_run+=( '_test' ) ;;
 
       # Compression and force compression arguments
       'c'|'C')
         # Skip as both compression arguments were already specified
         [[ "${conflicting[*]}" == *'-c, -C'* ]] && continue
 
-        operations[2]='_compress'
+        operations_to_run+=( '_compress' )
         [[ "$arg" == 'C' ]] && force_compression='true'
 
         # '-C' was already specified and '-c' is the current argument
@@ -1083,7 +1090,7 @@ _process_arguments()
         # Skip as both auCDtect arguments were already specified
         [[ "${conflicting[*]}" == *'-a, -A'* ]] && continue
 
-        operations[3]='_aucdtect'
+        operations_to_run+=( '_aucdtect' )
         [[ "$arg" == 'A' ]] && create_spectrogram='true'
 
         # '-A' was already specified and '-a' is the current argument
@@ -1101,7 +1108,7 @@ _process_arguments()
         # Skip as both LAC arguments were already specified
         [[ "${conflicting[*]}" == *'-l, -L'* ]] && continue
 
-        operations[8]='_lac'
+        operations_to_run+=( '_lac' )
         [[ "$arg" == 'L' ]] && create_spectrogram='true'
 
         # '-L' was already specified and '-l' is the current argument
@@ -1119,7 +1126,7 @@ _process_arguments()
         # Skip as both ReplayGain arguments were already specified
         [[ "${conflicting[*]}" == *'-g, -G'* ]] && continue
 
-        operations[4]='_replaygain'
+        operations_to_run+=( '_replaygain' )
         [[ "$arg" == 'G' ]] && force_replaygain='true'
 
         # '-G' was already specified and '-g' is the current argument
@@ -1133,13 +1140,13 @@ _process_arguments()
         ;;
 
       # Retag FLAC files
-      'r') operations[5]='_retag' ;;
+      'r') operations_to_run+=( '_retag' ) ;;
 
       # Extract embedded artwork from FLAC files
-      'e') operations[6]='_extract_images' ;;
+      'e') operations_to_run+=( '_extract_images' ) ;;
 
       # Prune unnecessary metadata blocks from FLAC files
-      'p') operations[7]='_prune' ;;
+      'p') operations_to_run+=( '_prune' ) ;;
 
       # Specify number of jobs/threads
       'j'|'J'|'T')
@@ -1208,6 +1215,36 @@ _process_arguments()
     _help
     exit 1
   fi
+
+  # Configure the order to run operations as this script may be called
+  # to run one or all operations on a target directory of FLAC files
+  if [[ " ${operations_to_run[*]} " =~ ' _md5check ' ]]; then
+    operations+=( '_md5check' )
+  fi
+  if [[ " ${operations_to_run[*]} " =~ ' _test ' ]]; then
+    operations+=( '_test' )
+  fi
+  if [[ " ${operations_to_run[*]} " =~ ' _compress ' ]]; then
+    operations+=( '_compress' )
+  fi
+  if [[ " ${operations_to_run[*]} " =~ ' _aucdtect ' ]]; then
+    operations+=( '_aucdtect' )
+  fi
+  if [[ " ${operations_to_run[*]} " =~ ' _lac ' ]]; then
+    operations+=( '_lac' )
+  fi
+  if [[ " ${operations_to_run[*]} " =~ ' _replaygain ' ]]; then
+    operations+=( '_replaygain' )
+  fi
+  if [[ " ${operations_to_run[*]} " =~ ' _retag ' ]]; then
+    operations+=( '_retag' )
+  fi
+  if [[ " ${operations_to_run[*]} " =~ ' _extract_images ' ]]; then
+    operations+=( '_extract_images' )
+  fi
+  if [[ " ${operations_to_run[*]} " =~ ' _prune ' ]]; then
+    operations+=( '_prune' )
+  fi
 }
 
 #
@@ -1223,13 +1260,13 @@ _check_missing_programs()
     type -P "$program" >/dev/null || missing_programs+=( "$program" )
   done
 
-  # auCDtect is the 4th index in $operations[@]
-  if [[ -n "${operations[3]}" ]]; then
+  # auCDtect binary
+  if [[ " ${operations[*]} " =~ ' _aucdtect ' ]]; then
     type -P auCDtect >/dev/null || missing_programs+=( 'auCDtect' )
   fi
 
-  # Lossless Audio Checker (LAC) is the 9th index in $operations[@]
-  if [[ -n "${operations[8]}" ]]; then
+  # Lossless Audio Checker (LAC) binary
+  if [[ " ${operations[*]} " =~ ' _lac ' ]]; then
     type -P LAC >/dev/null || missing_programs+=( 'LAC' )
   fi
 
@@ -2656,6 +2693,7 @@ do
     _error
   fi
 
+  # Rest of error messaging regardless of type of failure
   if [[ ! -d "${!dir}" || ! -w "${!dir}" ]]; then
     _error "Ensure a valid value for ${cyan}${dir}$reset is used"
     _error 'in the following configuration file:'
@@ -2869,7 +2907,7 @@ fi
 _runtime_banner
 
 # _retag(): Display a countdown
-[[ "${operations[5]}" == '_retag' ]] && _countdown_metadata
+[[ " ${operations[*]} " =~ ' _retag ' ]] && _countdown_metadata
 
 #
 # Obtain the total FLAC files to process (files and/or directories)
