feat: simplify cleanup and signal handling
Instead of having the _cleanup() function called twice via interrruption
and EXIT traps, the interruption traps set the global exit code and the
final EXIT trap calls the _cleanup() function to perform cleanup if the
user interrupted the script and safely ends the script, as it would
normally.

This simplifies having to check for abnormal and EXIT signals, and
instead performs action on abnormal signals and carries on with
additional cleanup.

Additionally, these changes make the cleanup handling atomic as the EXIT
trap can only be executed once, meaning a SIGINT followed by SIGTERM
will not cause collision as the _cleanup() function is run once during
EXIT only.

diff --git a/redoflacs b/redoflacs
--- a/redoflacs
+++ b/redoflacs
@@ -436,27 +436,24 @@ _print_item_skip() { printf "\033[${row}H${cyan}skip$reset";   }
 #
 # Manage termination and cleanup of this script
 #
-# The signal captured by this function is $1, generated by the trap
+# The signal processed by this function is via $exit_code, which, if
+# non-zero, is from a trap capturing a termination signal
 #
-# NOTE:
-#   This function may run twice, one for caught signals and one after
-#   script completion/exit
-#
-#   As a result, abnormal signals caught will perform cleanup by
-#   removing files and killing any jobs which may be running
+# Abnormal signals caught will perform cleanup by removing files and
+# killing any jobs which may be running
 #
 _cleanup()
 {
   local i fmt op match status_banner right_align
 
-  local signal_received="${1:-EXIT}"  # Signal received by trap
   local -i issues="$(_num_issues)"    # Total number of issues found
 
-  # Abnormal termination will terminate running jobs and remove
-  # temporary files
-  if [[ "$signal_received" != 'EXIT' ]]; then
-    _operation_title
-    _kill_jobs "$(jobs -rp)"
+  # If this global variable is non-zero, a trap caught an abnormal
+  # signal and redefined it to an exit code value matching the signal
+  # received
+  if (( exit_code != 0 )); then
+    _operation_title          # Display operation was interrupted
+    _kill_jobs "$(jobs -rp)"  # Kill any running jobs
 
     # Clear all the operation lines by moving up each line and clearing
     # it until we are just below the operation's title message
@@ -471,58 +468,50 @@ _cleanup()
 
     # Remove temporary picture blocks (from artwork extraction)
     rm -f /tmp/redoflacs_picture_blocks.[[:digit:]]*
-
-    # Define standard exit codes based on signal received
-    [[ "$signal_received" == 'SIGINT' ]] && exit_code=130
-    [[ "$signal_received" == 'SIGTERM' ]] && exit_code=143
   fi
 
-  if [[ "$signal_received" == 'EXIT' ]]; then
-    # Loop through all operations and display only the operations which
-    # have not run
-    for op in "${operations[@]}"; do
-      # Matched operation is either interrupted or completed with issues
-      [[ "$op" == "$operation" ]] && match='true' && continue
 
-      # Skip completed operations (without issues)
-      [[ ! "$match" ]] && continue
+  # Due to catching an abnormal signal or if there were issues found,
+  # loop through all operations and display any operation which did not
+  # run
+  for op in "${operations[@]}"; do
+    # Matched operation is either interrupted or completed with issues
+    [[ "$op" == "$operation" ]] && match='true' && continue
 
-      status_banner='DID NOT RUN'
+    # Skip completed operations (without issues)
+    [[ ! "$match" ]] && continue
 
-      # Determine where to place cursor in terminal column to right
-      # align the operation status
-      right_align=$(( MAX_LENGTH - ${#status_banner} ))
+    status_banner='DID NOT RUN'
 
-      fmt=" ${green}*$reset "  # Colored title prefix
-      fmt+='%s'                # Modifier; title of operation
+    # Determine where to place cursor in terminal column to right
+    # align the operation status
+    right_align=$(( MAX_LENGTH - ${#status_banner} ))
 
-      # Cursor at operation title; right-aligned for issues banner
-      fmt+=$"\033[$(_row);${right_align}H"
+    fmt=" ${green}*$reset "  # Colored title prefix
+    fmt+='%s'                # Modifier; title of operation
 
-      # Operation status banner
-      fmt+="${magenta}${status_banner}$reset\n"
+    # Cursor at operation title; right-aligned for issues banner
+    fmt+=$"\033[$(_row);${right_align}H"
 
-      # Display generated operation title message
-      printf "$fmt" "${operation_title[$op]}"
-    done
-  fi
+    # Operation status banner
+    fmt+="${magenta}${status_banner}$reset\n"
 
-  # Normal script termination checks for any logs and performs cleanup
-  # of script-created files
-  if [[ "$signal_received" == 'EXIT' ]]; then
-    # Ensure user is notified of a log file on script interruption/exit
-    [[ -f "$log_file" ]] && _display_issues_exist
+    # Display generated operation title message
+    printf "$fmt" "${operation_title[$op]}"
+  done
 
-    # Remove temporary job FIFO and temporary errors/issues file
-    rm -f "${job_fifo:-/dev/null/foo}"
-    rm -f "${issue_ticks:-/dev/null/foo}"
+  # Ensure user is notified of a log file on script interruption/exit
+  [[ -f "$log_file" ]] && _display_issues_exist
 
-    # Restore terminal cursor
-    printf '\033[?25h'
+  # Remove temporary job FIFO and temporary errors/issues file
+  rm -f "${job_fifo:-/dev/null/foo}"
+  rm -f "${issue_ticks:-/dev/null/foo}"
 
-    # Issues found without an abnormal signal
-    (( exit_code == 0 && issues > 0 )) && exit_code=1
-  fi
+  # Restore terminal cursor
+  printf '\033[?25h'
+
+  # Issues found without an abnormal signal
+  (( exit_code == 0 && issues > 0 )) && exit_code=1
 }
 
 #
@@ -2740,9 +2729,9 @@ export LC_ALL=C
 exit_code=0
 
 # Manage cleanup on interruption and script exit
-trap '_cleanup SIGINT; exit $exit_code' SIGINT
-trap '_cleanup SIGTERM; exit $exit_code' SIGTERM
-trap '_cleanup EXIT; exit $exit_code' EXIT
+trap 'exit_code=130; exit' SIGINT
+trap 'exit_code=143; exit' SIGTERM
+trap '_cleanup; exit $exit_code' EXIT
 
 # Hide cursor
 printf '\033[?25l'
